
import java.awt.Color;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JButton;
import javax.swing.JToggleButton;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class fourth extends javax.swing.JFrame {

    /**
     * Creates new form fourth
     */
    int sp1,gr1;
    public fourth()
    {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);  
    }
    public fourth(int s,int gr) {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);  
        sp1=s;
        gr1=gr;
        colour col=new colour(jButton2,jButton4,jButton5,jButton6,jButton7,jButton8,jButton9,sp1,gr1);
        col.start();
    }
    Color co = Color.BLACK;
    int sped = 10000, grd = 10;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 747));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT COLOR FOR GRID");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("WHITE");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 153, 255));
        jButton4.setText("BLUE");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 51));
        jButton5.setText("GREEN");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 0));
        jButton6.setText("YELLOW");

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 153, 0));
        jButton7.setText("ORANGE");
        jButton7.setToolTipText("");

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 51, 204));
        jButton8.setText("PINK");

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 204, 204));
        jButton9.setText("GRAY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
     Color c = null;
       /* if(jButton1.getBackground()==Color.CYAN)
        {
            c=Color.BLACK;
        }*/
        if(jButton2.getBackground()==Color.CYAN)
        {
            c=Color.WHITE;
        }
        /*else if(jButton3.getBackground()==Color.CYAN)
        {
            c=Color.RED;
            
        }*/
         else if(jButton4.getBackground()==Color.CYAN)
        {
            c=Color.BLUE;
            
        }
         else if(jButton5.getBackground()==Color.CYAN)
        {
            c=Color.GREEN;
            
        }
         else if(jButton6.getBackground()==Color.CYAN)
        {
            c=Color.YELLOW;
            
        }
         else if(jButton7.getBackground()==Color.CYAN)
        {
            c=Color.ORANGE;
            
        }
         else if(jButton8.getBackground()==Color.CYAN)
        {
            c=Color.PINK;
            
        }
         else if(jButton9.getBackground()==Color.CYAN)
        {
            c=Color.DARK_GRAY;
            
        }
        
        Step s=new Step(sp1,gr1,c);
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fourth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fourth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fourth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fourth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fourth().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
class colour extends Thread {

    JButton  b2,b4, b5, b6, b7, b8, b9;
    int i,spe,gri;
    

    colour( JButton b, JButton d, JButton e, JButton f, JButton g, JButton h, JButton j,int s,int gr)
    {
        //b1 = a;
        b2 = b;
        //b3 = c;
        b4 = d;
        b5 = e;
        b6 = f;
        b7 = g;
        b8 = h;
        b9 = j;
        i=-1;
        spe=s;
        gri=gr;
    }

    @Override
    public void run() {
        while (true) {
          //   b1.setBackground(Color.LIGHT_GRAY);
             b2.setBackground(Color.LIGHT_GRAY);
            // b3.setBackground(Color.LIGHT_GRAY);
             b4.setBackground(Color.LIGHT_GRAY);
             b5.setBackground(Color.LIGHT_GRAY);
             b6.setBackground(Color.LIGHT_GRAY);
             b7.setBackground(Color.LIGHT_GRAY);
             b8.setBackground(Color.LIGHT_GRAY);
             b9.setBackground(Color.LIGHT_GRAY);
             //b1.setForeground(Color.BLACK);
             b2.setForeground(Color.WHITE);
             //b3.setForeground(Color.RED);
             b4.setForeground(Color.BLUE);
             b5.setForeground(Color.GREEN);
             b6.setForeground(Color.YELLOW);
             b7.setForeground(Color.ORANGE);
             b8.setForeground(Color.PINK);
             b9.setForeground(Color.DARK_GRAY);
            /*b1.setEnabled(false);
            b2.setEnabled(false);
            b3.setEnabled(false);
            b4.setEnabled(false);
            b5.setEnabled(false);
            b6.setEnabled(false);
            b7.setEnabled(false);
            b8.setEnabled(false);
            b9.setEnabled(false);*/
           
            i = (i + 1) % 7;

            if (i == 0)
            {
                //b1.setBackground(Color.CYAN);
                b2.setBackground(Color.CYAN);
  //              b3.setBackground(Color.LIGHT_GRAY);
                b4.setBackground(Color.LIGHT_GRAY);
                b5.setBackground(Color.LIGHT_GRAY);
                b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
            }
           else 
            if (i == 1)
            {
                b2.setBackground(Color.LIGHT_GRAY);
    //            b1.setBackground(Color.LIGHT_GRAY);
      //          b3.setBackground(Color.LIGHT_GRAY);
                b4.setBackground(Color.CYAN);
                b5.setBackground(Color.LIGHT_GRAY);
                b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
            }
            else
            if (i == 2) 
            {
               // b3.setBackground(Color.CYAN);
                b2.setBackground(Color.LIGHT_GRAY);
                //b1.setBackground(Color.LIGHT_GRAY);
                b4.setBackground(Color.LIGHT_GRAY);
                b5.setBackground(Color.CYAN);
                b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
            }
            else
            if (i == 3)
            {
                b4.setBackground(Color.LIGHT_GRAY);
                b2.setBackground(Color.LIGHT_GRAY);
               // b3.setBackground(Color.LIGHT_GRAY);
                //b1.setBackground(Color.LIGHT_GRAY);
                b5.setBackground(Color.LIGHT_GRAY);
                b6.setBackground(Color.CYAN);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
            }
            else
            if (i == 4)
            {
                b5.setBackground(Color.LIGHT_GRAY);
                b2.setBackground(Color.LIGHT_GRAY);
                //b3.setBackground(Color.LIGHT_GRAY);
                b4.setBackground(Color.LIGHT_GRAY);
               // b1.setBackground(Color.LIGHT_GRAY);
                b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.CYAN);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
            }
            else
            if (i == 5)
            {
                b6.setBackground(Color.LIGHT_GRAY);
                b2.setBackground(Color.LIGHT_GRAY);
                //b3.setBackground(Color.LIGHT_GRAY);
                b4.setBackground(Color.LIGHT_GRAY);
                b5.setBackground(Color.LIGHT_GRAY);
                //b1.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.CYAN);
                b9.setBackground(Color.LIGHT_GRAY);
            }
            else
            if (i == 6)
            {
                b7.setBackground(Color.LIGHT_GRAY);
                b2.setBackground(Color.LIGHT_GRAY);
               // b3.setBackground(Color.LIGHT_GRAY);
                b4.setBackground(Color.LIGHT_GRAY);
                b5.setBackground(Color.LIGHT_GRAY);
                b6.setBackground(Color.LIGHT_GRAY);
                //b1.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.CYAN);
            } 
           
            try {

                Thread t = Thread.currentThread();
                t.setPriority(Thread.MAX_PRIORITY);

                Thread.sleep(spe);

                //t.join();
            } catch (Exception e) {
            }
        }
      
    }
}
