
import java.awt.Color;
import javax.swing.JButton;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class func extends javax.swing.JFrame {

    /**
     * Creates new form func
     */
  int ste,grid,num,speed;
  int[] val;
  Color colo;
    public func() 
    {
        initComponents();
         this.getContentPane().setBackground(Color.BLACK);
  // fun fu=new fun(jButton1,jButton2,speed);
    // fu.start();
    }
public func(int step,int spe,int arr[],int gri,Color col,int n1)
{
    initComponents();
     this.getContentPane().setBackground(Color.BLACK);
     ste=step;
     grid=gri;
     speed=spe;
     num=n1;
     colo=col;
     val=new int[num];
      for(int i=0;i<num;i++)
        {
            val[i]= arr[i];
            System.out.println(val[i]);
            System.out.println(arr[i]);
        }
    fun fu=new fun(jButton1,jButton2,speed);
     fu.start(); 
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 747));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton1.setText("Y=X+1");

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton2.setText("Y=5X-4");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("CHOOSE FUNCTION TO PLOT:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(254, 254, 254))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(312, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
         Color c1,c2;
        int s = 0;
        c1=jButton1.getBackground();
        c2=jButton2.getBackground();
       // c3=jButton3.getBackground();
        if(c1==Color.RED)
        {
            graph gr=new graph(ste,val,grid,colo,num);
        gr.setVisible(true);
        this.setVisible(false);
        }
        else
            if(c2==Color.RED)
            {
                graph1 gr1=new graph1(ste,val,grid,colo,num);
            gr1.setVisible(true);
        this.setVisible(false);
            }
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new func().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
class fun extends Thread
    {
        JButton b1, b2;
        int i;
        int speed;
        fun(JButton a,JButton b,int spee)
        {
            i=-1;
            b1=a;
            b2=b;
            speed=spee;
      
            //start();
        }
        public void run()
        {
            
            while(true)
            {
                /*b1.setEnabled(false);
                //b1.setBackground(Color.BLUE);
                b2.setEnabled(false);
                b3.setEnabled(false);*/
                b1.setForeground(Color.BLACK);
                b2.setForeground(Color.BLACK);
           //     b3.setForeground(Color.BLACK);
                b1.setBackground(Color.LIGHT_GRAY);
                b2.setBackground(Color.LIGHT_GRAY);
             //   b3.setBackground(Color.LIGHT_GRAY);
                
                i = ( i + 1 ) % 2;
                if(i == 0)
                {
                    //b1.setEnabled(true);
                    b2.setBackground(Color.LIGHT_GRAY);
               //     b3.setBackground(Color.LIGHT_GRAY);
                    b1.setBackground(Color.RED);
                }
                else 
                    if(i==1)
                    {
                        //b2.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                 //       b3.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.RED);
                    }
              
                try {

                Thread t = Thread.currentThread();
                Thread.sleep(speed);
                }
                catch (Exception e)
                {}
            }
        }
    }

