
import java.awt.Color;
import javax.swing.JButton;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */

public class input extends javax.swing.JFrame {

    /**
     * Creates new form input
     */
    int i=0,n1;
    int[] arr;
    int step,spe,gri;
    Color col;
    public input() {
        initComponents();
         this.getContentPane().setBackground(Color.BLACK);
    }
    public input(int st,int speed,int grid, Color colour,int no)
    {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        step=st;
        spe=speed;
        gri=grid;
        col=colour; 
        n1=no;
        arr=new int[n1];
         inp in=new inp(jButton1,jButton2,jButton3,jButton4,jButton5,jButton6,jButton7,jButton8,jButton9,jButton10,jButton11,jButton12,jButton13,speed);
         in.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 747));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton1.setText("6");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton2.setText("8");

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton3.setText("7");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton4.setText("10");

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton5.setText("9");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton6.setText("5");

        jButton7.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton7.setText("11");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton8.setText("12");

        jButton9.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton9.setText("13");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton10.setText("1");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton11.setText("2");

        jButton12.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton12.setText("3");

        jButton13.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton13.setText("4");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CHOOSE INPUT VALUES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(320, 320, 320)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(320, 320, 320)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(168, 168, 168))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        Color c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13;
        
        c1=jButton1.getBackground();
        c2=jButton2.getBackground();
        c3=jButton3.getBackground();
        c4=jButton4.getBackground();
        c5=jButton5.getBackground();
         c6=jButton6.getBackground();
        c7=jButton7.getBackground();
        c8=jButton8.getBackground();
        c9=jButton9.getBackground();
        c10=jButton10.getBackground();
         c11=jButton11.getBackground();
        c12=jButton12.getBackground();
        c13=jButton13.getBackground();
     
        if(c1==Color.BLUE)
        {
            arr[i]=6;
            //System.out.format("\n%d,%d",i,arr[i]);
            i++;
               
        }
        else
            if(c2==Color.BLUE)
            {
                arr[i]=8;
                //System.out.format("\n%d,%d",i,arr[i]);
                i++;
                   
            }
        else
                if(c3==Color.BLUE)
                {
                    arr[i]=7;
                    //System.out.format("\n%d,%d",i,arr[i]);
                    i++;
                       
                }
        else
                    if(c4==Color.BLUE)
                {
                    arr[i]=10;
                    //System.out.format("\n%d,%d",i,arr[i]);
                    i++;
                      
                }
        else
                    if(c5==Color.BLUE)
                {
                    arr[i]=9;
                    //System.out.format("\n%d,%d",i,arr[i]);
                    i++;
                     
  }
   else  if(c6==Color.BLUE)
        {
            arr[i]=5;
            //System.out.format("\n%d,%d",i,arr[i]);
            i++;
               
        }
        else
            if(c7==Color.BLUE)
            {
                arr[i]=11;
                //System.out.format("\n%d,%d",i,arr[i]);
                i++;
                   
            }
        else
                if(c8==Color.BLUE)
                {
                    arr[i]=12;
                    //System.out.format("\n%d,%d",i,arr[i]);
                    i++;
                       
                }
        else
                    if(c9==Color.BLUE)
                {
                    arr[i]=13;
                    //System.out.format("\n%d,%d",i,arr[i]);
                    i++;
                      
                }
        else
                    if(c10==Color.BLUE)
                {
                    arr[i]=1;
                    //System.out.format("\n%d,%d",i,arr[i]);
                    i++;
                     
  }
          else  if(c11==Color.BLUE)
        {
            arr[i]=2;
            //System.out.format("\n%d,%d",i,arr[i]);
            i++;
               
        }
        else
            if(c12==Color.BLUE)
            {
                arr[i]=3;
                //System.out.format("\n%d,%d",i,arr[i]);
                i++;
                   
            }
        else
                if(c13==Color.BLUE)
                {
                    arr[i]=4;
                    //System.out.format("\n%d,%d",i,arr[i]);
                    i++;
                       
                }
    if(i==n1)
        { 
          /*  for(int i=0;i<n1;i++)
            {
                System.out.format("\n%d", arr[i]);
            }*/
        
        func func1=new func(step,spe,arr,gri,col,n1);
          func1.setVisible(true);
        //ch.setVisible(true);
        this.setVisible(false);
    }
 /*      if(i==5)
        { 
        graph gr=new graph(step,arr,gri,col);
        gr.setVisible(true);
        //ch.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formMouseClicked
    }*/
}
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
class inp extends Thread
{
   
        JButton b1, b2, b3,b4,b5,b6,b7,b8,b9,b10,b11,b12,b13;
        int i,spee;
        inp(JButton a,JButton b,JButton c,JButton d,JButton e,JButton f,JButton g,JButton h,JButton j,JButton k,JButton l,JButton m,JButton n,int speed)
        {
            i=-1;
            b1=a;
            b2=b;
            b3=c;
            b4=d;
            b5=e;
            b6=f;
            b7=g;
            b8=h;
            b9=j;
            b10=k;
            b11=l;
            b12=m;
            b13=n;
            spee=speed;
        }       
        public void run()
        {
            
            while(true)
            {
              
                b1.setForeground(Color.BLACK);
                b2.setForeground(Color.BLACK);
                b3.setForeground(Color.BLACK);
                b4.setForeground(Color.BLACK);
                b5.setForeground(Color.BLACK);
                b6.setForeground(Color.BLACK);
                b7.setForeground(Color.BLACK);
                b8.setForeground(Color.BLACK);
                b9.setForeground(Color.BLACK);
                 b10.setForeground(Color.BLACK);
                b11.setForeground(Color.BLACK);
                b12.setForeground(Color.BLACK);
                b13.setForeground(Color.BLACK);
                b1.setBackground(Color.LIGHT_GRAY);
                b2.setBackground(Color.LIGHT_GRAY);
                b3.setBackground(Color.LIGHT_GRAY);
                b4.setBackground(Color.LIGHT_GRAY);
                b5.setBackground(Color.LIGHT_GRAY);
                b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
                 b10.setBackground(Color.LIGHT_GRAY);
                b11.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.LIGHT_GRAY);
                b13.setBackground(Color.LIGHT_GRAY);
                i = ( i + 1 ) % 13;
                if(i == 0)
                {
                    //b1.setEnabled(true);
                    b2.setBackground(Color.LIGHT_GRAY);
                    b3.setBackground(Color.LIGHT_GRAY);
                    b4.setBackground(Color.LIGHT_GRAY);
                    b5.setBackground(Color.LIGHT_GRAY);
                    b1.setBackground(Color.LIGHT_GRAY);
                     b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
                b11.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.LIGHT_GRAY);
                b13.setBackground(Color.LIGHT_GRAY);
                b10.setBackground(Color.BLUE);
                }
                else 
                    if(i==1)
                    {
                        //b2.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.LIGHT_GRAY);
                    b5.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                         b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
                 b10.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.LIGHT_GRAY);
                b13.setBackground(Color.LIGHT_GRAY);
                b11.setBackground(Color.BLUE);
                    }
                    else if(i==2)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.LIGHT_GRAY);
                    b5.setBackground(Color.LIGHT_GRAY);
                    b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                         b10.setBackground(Color.LIGHT_GRAY);
                b11.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.BLUE);
                        b13.setBackground(Color.LIGHT_GRAY);
                        
                    }
                 else if(i==3)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                        b5.setBackground(Color.LIGHT_GRAY);
                    b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.LIGHT_GRAY);
                          b10.setBackground(Color.LIGHT_GRAY);
                b11.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.LIGHT_GRAY);
                        b13.setBackground(Color.BLUE);
                    }
                 else if(i==4)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.LIGHT_GRAY);
                       b5.setBackground(Color.LIGHT_GRAY);
                        b6.setBackground(Color.BLUE);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
                   b10.setBackground(Color.LIGHT_GRAY);
                        b11.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.LIGHT_GRAY);
                b13.setBackground(Color.LIGHT_GRAY);
                    }
                
                 else if(i==5)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.BLUE);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.LIGHT_GRAY);
                       b5.setBackground(Color.LIGHT_GRAY);
                        b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
                     b10.setBackground(Color.LIGHT_GRAY);
                        b11.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.LIGHT_GRAY);
                b13.setBackground(Color.LIGHT_GRAY);
                    }
                 else if(i==6)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.BLUE);
                        b4.setBackground(Color.LIGHT_GRAY);
                       b5.setBackground(Color.LIGHT_GRAY);
                        b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
                     b10.setBackground(Color.LIGHT_GRAY);
                        b11.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.LIGHT_GRAY);
                b13.setBackground(Color.LIGHT_GRAY);
                    }
                 else if(i==7)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.BLUE);
                        b3.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.LIGHT_GRAY);
                       b5.setBackground(Color.LIGHT_GRAY);
                     b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
                     b10.setBackground(Color.LIGHT_GRAY);
                        b11.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.LIGHT_GRAY);
                b13.setBackground(Color.LIGHT_GRAY);
                    }
                 else if(i==8)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.LIGHT_GRAY);
                       b5.setBackground(Color.BLUE);
                     b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
                     b10.setBackground(Color.LIGHT_GRAY);
                        b11.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.LIGHT_GRAY);
                b13.setBackground(Color.LIGHT_GRAY);
                    }
                 else if(i==9)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.BLUE);
                       b5.setBackground(Color.LIGHT_GRAY);
                     b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
                     b10.setBackground(Color.LIGHT_GRAY);
                        b11.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.LIGHT_GRAY);
                b13.setBackground(Color.LIGHT_GRAY);
                    }
                else if(i==10)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.LIGHT_GRAY);
                       b5.setBackground(Color.LIGHT_GRAY);
                     b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.BLUE);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.LIGHT_GRAY);
                     b10.setBackground(Color.LIGHT_GRAY);
                        b11.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.LIGHT_GRAY);
                b13.setBackground(Color.LIGHT_GRAY);
                    }
                else if(i==11)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.LIGHT_GRAY);
                       b5.setBackground(Color.LIGHT_GRAY);
                     b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.BLUE);
                b9.setBackground(Color.LIGHT_GRAY);
                     b10.setBackground(Color.LIGHT_GRAY);
                        b11.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.LIGHT_GRAY);
                b13.setBackground(Color.LIGHT_GRAY);
                    }
                else if(i==12)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.LIGHT_GRAY);
                       b5.setBackground(Color.LIGHT_GRAY);
                     b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                b8.setBackground(Color.LIGHT_GRAY);
                b9.setBackground(Color.BLUE);
                     b10.setBackground(Color.LIGHT_GRAY);
                        b11.setBackground(Color.LIGHT_GRAY);
                b12.setBackground(Color.LIGHT_GRAY);
                b13.setBackground(Color.LIGHT_GRAY);
                    }
               
                try {

                Thread t = Thread.currentThread();
                Thread.sleep(spee);
                }
                catch (Exception e)
                {}
            }
        }
    }

