
import java.awt.Color;
import javax.swing.JButton;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class Step extends javax.swing.JFrame {

    /**
     * Creates new form Step
     */
    int speed,grid;
    Color colour;
    public Step() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
       // stepunit s1=new stepunit(jButton4,jButton2,jButton3,jButton1,jButton6,jButton5,jButton7);
        //s1.start();
       
    }
    public Step(int spee,int gri,Color col)
    {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        speed=spee;
        grid=gri;
        colour=col;
        stepunit s1=new stepunit(jButton4,jButton2,jButton3,jButton1,jButton6,jButton5,jButton7,speed);
        s1.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 747));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CHOOSE SCALE");

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton1.setText("4");

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton2.setText("2");

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton4.setText("1");

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton5.setText("10");

        jButton6.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton6.setText("5");

        jButton7.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jButton7.setText("20");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(350, 350, 350)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(500, 500, 500)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(450, 450, 450))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       
        Color c1,c2,c3,c4,c5,c6,c7;
        int st = 0;
        c1=jButton1.getBackground();
        c2=jButton2.getBackground();
        c3=jButton3.getBackground();
        c4=jButton4.getBackground();
        c5=jButton5.getBackground();
        c6=jButton6.getBackground();
        c7=jButton7.getBackground();
        if(c1==Color.BLUE)
        {
            st=4;
        }
        else
            if(c2==Color.BLUE)
            {
                st=2;
            }
        else
                if(c3==Color.BLUE)
                {
                    st=3;
                }
        else
                    if(c4==Color.BLUE)
                {
                    st=1;
                }
        else
                    if(c5==Color.BLUE)
                {
                    st=10;
                }
                         
        else
                    if(c6==Color.BLUE)
                {
                    st=5;
                }
         
        else
                    if(c7==Color.BLUE)
                {
                    st=20;
                }  
                   
        number n=new number(st,speed,grid,colour);
        n.setVisible(true);
        //ch.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Step.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Step.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Step.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Step.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Step().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
class stepunit extends Thread
    {
        JButton b1, b2, b3,b4,b5,b6,b7;
        int i,speed;
        stepunit(JButton a,JButton b,JButton c,JButton d,JButton e,JButton f,JButton g,int spe)
        {
            i=-1;
            b1=a;
            b2=b;
            b3=c;
            b4=d;
            b5=e;
            b6=f;
            b7=g;
            speed=spe;
        }       
        public void run()
        {
            
            while(true)
            {
                /*b1.setEnabled(false);
                //b1.setBackground(Color.BLUE);
                b2.setEnabled(false);
                b3.setEnabled(false);*/
                b1.setForeground(Color.BLACK);
                b2.setForeground(Color.BLACK);
                b3.setForeground(Color.BLACK);
                b4.setForeground(Color.BLACK);
                b5.setForeground(Color.BLACK);
                b6.setForeground(Color.BLACK);
                b7.setForeground(Color.BLACK);
                b1.setBackground(Color.LIGHT_GRAY);
                b2.setBackground(Color.LIGHT_GRAY);
                b3.setBackground(Color.LIGHT_GRAY);
                b4.setBackground(Color.LIGHT_GRAY);
                b5.setBackground(Color.LIGHT_GRAY);
                b6.setBackground(Color.LIGHT_GRAY);
                b7.setBackground(Color.LIGHT_GRAY);
                
                i = ( i + 1 ) % 7;
                if(i == 0)
                {
                    //b1.setEnabled(true);
                    b2.setBackground(Color.LIGHT_GRAY);
                    b3.setBackground(Color.LIGHT_GRAY);
                    b4.setBackground(Color.LIGHT_GRAY);
                    b5.setBackground(Color.LIGHT_GRAY);
                    b6.setBackground(Color.LIGHT_GRAY);
                    b7.setBackground(Color.LIGHT_GRAY);
                    b1.setBackground(Color.BLUE);
                }
                else 
                    if(i==1)
                    {
                        //b2.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.LIGHT_GRAY);
                    b5.setBackground(Color.LIGHT_GRAY);
                    b6.setBackground(Color.LIGHT_GRAY);
                    b7.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.BLUE);
                    }
                    else if(i==2)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.LIGHT_GRAY);
                    b5.setBackground(Color.LIGHT_GRAY);
                    b6.setBackground(Color.LIGHT_GRAY);
                    b7.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.BLUE);
                    }
                 else if(i==3)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                    b5.setBackground(Color.LIGHT_GRAY);
                    b6.setBackground(Color.LIGHT_GRAY);
                    b7.setBackground(Color.LIGHT_GRAY);
                        b4.setBackground(Color.BLUE);
                    }
                 else if(i==4)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                    b4.setBackground(Color.LIGHT_GRAY);
                    b6.setBackground(Color.LIGHT_GRAY);
                    b7.setBackground(Color.LIGHT_GRAY);
                        b5.setBackground(Color.BLUE);
                    }
                 else if(i==5)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                    b4.setBackground(Color.LIGHT_GRAY);
                    b5.setBackground(Color.LIGHT_GRAY);
                    b7.setBackground(Color.LIGHT_GRAY);
                        b6.setBackground(Color.BLUE);
                    }
                 else if(i==6)
                    {
                        //b3.setEnabled(true);
                        b1.setBackground(Color.LIGHT_GRAY);
                        b2.setBackground(Color.LIGHT_GRAY);
                        b3.setBackground(Color.LIGHT_GRAY);
                    b4.setBackground(Color.LIGHT_GRAY);
                    b5.setBackground(Color.LIGHT_GRAY);
                    b6.setBackground(Color.LIGHT_GRAY);
                        b7.setBackground(Color.BLUE);
                    }
                
                try {

                Thread t = Thread.currentThread();
                Thread.sleep(speed);
                }
                catch (Exception e)
                {}
            }
        }
    }
